name: Build and Package for ArchLinux

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ---------- 1. 初始化 ----------
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true  # 启用缓存
          cache-dependency-path: go.sum  # 指定缓存依赖文件

      # ---------- 2. 生成依赖文件 ----------
      - name: Initialize Go Modules
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/Duter2016/hiwifi-ssh-launcher
          fi
          go mod tidy
          
      # ---------- 3. 构建二进制 ----------
      - name: Build Binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o hiwifi-ssh-launcher .
          strip hiwifi-ssh-launcher

      # ---------- 4. 安装打包工具 ----------
      - name: Install Packaging Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            binutils \
            fakeroot \
            file \
            libarchive-tools \
            curl
          
          # 安装精简版makepkg
          sudo curl -L https://raw.githubusercontent.com/archlinux/archlinux-container/main/rootfs/usr/bin/makepkg -o /usr/bin/makepkg
          sudo chmod +x /usr/bin/makepkg

      # ---------- 5. 创建PKGBUILD ----------
      - name: Create Package Files
        run: |
          VERSION=${GITHUB_REF##*/v}
          [ -z "$VERSION" ] || [ "$VERSION" = "$GITHUB_REF" ] && VERSION="0.0.1"
          
          cat <<EOF > PKGBUILD
          pkgname=hiwifi-ssh-launcher
          pkgver=$VERSION
          pkgrel=1
          pkgdesc="SSH Launcher for HiWiFi"
          arch=('x86_64')
          license=('MIT')
          source=("\$pkgname-\$pkgver.tar.gz")
          sha256sums=('SKIP')

          build() {
            cd "\$pkgname-\$pkgver"
            go build -ldflags="-s -w" -o \$pkgname .
          }

          package() {
            install -Dm755 "\$srcdir/\$pkgname-\$pkgver/\$pkgname" "\$pkgdir/usr/bin/\$pkgname"
          }
          EOF

          tar -czf "hiwifi-ssh-launcher-$VERSION.tar.gz" --transform "s,^,hiwifi-ssh-launcher-$VERSION/," *

      # ---------- 6. 构建软件包 ----------
      - name: Build Package
        run: |
          makepkg -s --noconfirm SKIPCHECKSUMS SKIPPGPCHECK

      # ---------- 7. 上传产物 ----------
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            hiwifi-ssh-launcher
            *.pkg.tar.zst
