name: ArchLinux Package Builder

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o hiwifi-ssh-launcher .
          strip hiwifi-ssh-launcher

      - name: Prepare package files
        run: |
          mkdir pkg
          cp hiwifi-ssh-launcher pkg/
          [ -f LICENSE ] && cp LICENSE pkg/
          
          VERSION=${GITHUB_REF#refs/tags/v}
          [ -z "$VERSION" ] && VERSION="1.0.0"

          cat <<EOF > pkg/PKGBUILD
pkgname=hiwifi-ssh-launcher
pkgver=$VERSION
pkgrel=1
pkgdesc="SSH Launcher for HiWiFi"
arch=('x86_64')
license=('MIT')

package() {
  install -Dm755 hiwifi-ssh-launcher "\${pkgdir}/usr/bin/hiwifi-ssh-launcher"
}
EOF

      - name: Build package
        run: |
          cd pkg
          docker run --rm -v $(pwd):/build -w /build archlinux:latest bash -c "
            echo 'Server = https://mirrors.ustc.edu.cn/archlinux/\$repo/os/\$arch' > /etc/pacman.d/mirrorlist
            pacman -Sy --noconfirm base-devel &&
            makepkg -s --noconfirm
          "
          cp *.pkg.tar.zst ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hiwifi-package
          path: "*.pkg.tar.zst"
