name: Build and Package for ArchLinux

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 初始化
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # 2. 构建二进制
      - name: Build Binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o hiwifi-ssh-launcher .
          strip hiwifi-ssh-launcher

      # 3. 准备Arch打包
      - name: Prepare Arch Package
        run: |
          mkdir -p arch-build
          cp hiwifi-ssh-launcher go.mod arch-build/
          [ -f go.sum ] && cp go.sum arch-build/
          [ -f LICENSE ] && cp LICENSE arch-build/
          
          VERSION=${GITHUB_REF#refs/tags/v}
          [ -z "$VERSION" ] && VERSION="0.0.1"

          cat > arch-build/PKGBUILD << 'EOL'
pkgname=hiwifi-ssh-launcher
pkgver=VERSION_PLACEHOLDER
pkgrel=1
pkgdesc="SSH Launcher"
arch=('x86_64')
license=('MIT')

source=("${pkgname}-${pkgver}.tar.gz")

package() {
  install -Dm755 "$srcdir/${pkgname}-${pkgver}/hiwifi-ssh-launcher" "$pkgdir/usr/bin/$pkgname"
}
EOL
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/g" arch-build/PKGBUILD
          mkdir -p "arch-build/hiwifi-ssh-launcher-$VERSION"
          cp arch-build/* "arch-build/hiwifi-ssh-launcher-$VERSION"/ 2>/dev/null || true
          cd arch-build && tar -czf "hiwifi-ssh-launcher-$VERSION.tar.gz" "hiwifi-ssh-launcher-$VERSION"

      # 4. 容器内构建
      - name: Build in Docker
        run: |
          cd arch-build
          docker run --rm -v $(pwd):/build -w /build archlinux:latest bash -c "
            echo 'Server = https://mirrors.ustc.edu.cn/archlinux/\$repo/os/\$arch' > /etc/pacman.d/mirrorlist
            pacman -Sy --noconfirm base-devel &&
            makepkg -s --noconfirm SKIPCHECKSUMS SKIPPGPCHECK
          "
          [ -f *.pkg.tar.zst ] && cp *.pkg.tar.zst ../

      # 5. 上传结果
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-pkg
          path: |
            hiwifi-ssh-launcher
            *.pkg.tar.zst
